appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: X39rFjv8rLvd7k0A7V1EMhybjj98RC36oL50XLxnc7gXydwVjXLZKtRZdaZuf1qrxxcNmC78Ppkn+g4yn/Io7neXmgu+1NcIDvi+FfIZCeMwXkzB9BoFRO6y9hvBhfNRjoV0PTHPq5KFEaRgG5OuQS8SqjzWSXugFNOdARl2yRm9M3QZWbmStGoQJlh6hArdOC68Jgu+/F+nxszvn8OJJCs7mMycyKVvBZEyejur/fLB7QgLaTT0qE+cpqHsUmWVHzTgeZYtLJvznLYq9OIWWbnzPCsQhi124zYDkTWOfFVFlLnY+LjdaohNp9fONXHdoplO8EjeC8uEyLm29jppvMplLQVysCeVtRtvjtIgCLnlQeGrLJxtsQINXDQVPMjjltgx8bBCV7uhvAMnM8Z3RekpEpXaaM/0CyZoU6yO0EmY7tvjyZ8Ejp38sxEkEYuVJJnJGxfoznqeoYHuAApcDtNh86ugAk5HHSg56Dg68PMOBqU7UzbmK4+Wiq7eBjT6OlAAlC9Jvs/vwrHINC7NnghYRzvFEaPI7P72MnYc3ZERN63FFxNWib+JWSA0J7zjJzfofHD4+NMNaw45HGMZs55ZYwCvGIC5ekH0yv0UrejOXAP4o89uB9nbNyZsLqSrr4SeddPnJBtFoZZrcyejmIH0VsRsctAM7ImkXdQgGSY=
